Initialize HR Portal with basic structure and configuration
IgniteUI/grid-demos pull request #1
Opened 2024-12-02 13:35 UTC by tishko0

2024-12-04 09:57 UTC, skrustev requested changes

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/.github/workflows/node.js.yml
> +name: Node.js CI
Any folder that is locally created when opening the app  or not relevant shouldn't be committed  like the .github and .vscode ones.
Also under `src/app/assets/,gitkeep`

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/server.ts
> +export function app(): express.Express {
Why this file is not in the `src/` folder like the rest?

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +    this.iconService.addSvgIcon('linkedIn', 'assets/images/others/linkedin.svg', 'hr-icons');
All images that are seen and available to the users should be in the `public/` folder since angular 18.

Also too much duplication of code for registering the SVGs. This could be a cycle that loops around an array containing info for the country and its SVG, with common path used for all.

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/angular.json
> +              "src/favicon.ico",
This should also be updated since from angular 18 onward the convention is that main assets are under the `public/` folder. Should be updated to:
```
"assets": [
    {
        "glob": "**/*",
        "input": "public"
    }
],
``

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/app.component.html
> +  <app-tree-grid1></app-tree-grid1>
The name is too generic and not really a good practice to show. At least should be somewhat descriptive of what component is. `tree-grid1` doesn't say much.

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.scss
> +@use "igniteui-angular/theming" as *;
Importing theming again?
This should be done in the root `styels.css`

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +import { AfterViewInit, Component, OnInit, ViewChild, viewChild } from '@angular/core';
`AfterViewInit` and `viewChild` are not used anywhere.

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +import { IgxTreeGridComponent, IgxColumnComponent, IgxAvatarComponent, IgxPaginatorComponent, IgxGridToolbarComponent, IgxGridToolbarActionsComponent, IgxGridToolbarHidingComponent, IgxGridToolbarAdv
`IgxButtonGroupComponent` is also not used anywhere. Also could you format it on multiple lines so the import is not 500 characters long?

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +  title = 'HR Portal - IgniteUI for Angular';
This title doesn't seem to be used anywhere?

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.html
> +<igx-paginator [perPage]="20"></igx-paginator>
The tabulation of the whole section is very confusing. Please format it so it respects child levels.

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.html
> +        <!-- <a [href]="'mailto:' + cell.row.data.Contacts" (click)="$event.stopPropagation()">
Maybe a leftover?

2024-12-04 09:57 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +  constructor(private iconService: IgxIconService, private http: HttpClient) { }
HttpClient doesn't seem to be used anywhere.
Also some empty rows extra around.

2024-12-04 10:00 UTC, skrustev commented
Also could you move the whole `HR-Portal` project folder under `.projects/` at least for now. Until we figure out the main app and its structure.

2024-12-04 10:30 UTC, skrustev commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.spec.ts
> +      imports: [BrowserAnimationsModule, IgxTreeGridModule, IgxDatePickerModule, IgxCheckboxModule, TreeGrid1Component]
Are these other components being tested as well? Not that in general we'll write test but this seems taken from somewhere unrelated.

2024-12-05 09:53 UTC, sbayreva commented
1. Missing “Clear sort” button. The order of the button is different from the design in Figma

Implementation:
<img width="608" alt="Screenshot 2024-12-04 at 15 31 47" src="https://github.com/user-attachments/assets/3230de17-ebb5-4bf3-931f-210b3b6ba0ba">

Figma design:
<img width="669" alt="Screenshot 2024-12-04 at 15 33 48" src="https://github.com/user-attachments/assets/d554ee80-3b97-4b0b-b0df-2736fb89fb38">



2. This header should have sorting icon
<img width="248" alt="Screenshot 2024-12-04 at 17 11 25" src="https://github.com/user-attachments/assets/d6aafebe-cbb9-4aa9-92a5-3182d513b4c5">



3. “Contacts” should **not** have filtering
<img width="244" alt="Screenshot 2024-12-04 at 17 12 30" src="https://github.com/user-attachments/assets/3b5ae95f-30b0-4fbf-8d06-9a10d3adb6c4">




4.  The header of “Gross Salary” column should have filtering + sorting. The column should have some data. In Figma the column is populated with data, but probably you can’t see it because of some permissions

Implementation header:
<img width="189" alt="Screenshot 2024-12-04 at 17 13 59" src="https://github.com/user-attachments/assets/17a10f65-371b-4412-ad1d-bc0f9c6cd546">

Figma, “Gross Salary” column:
<img width="106" alt="Screenshot 2024-12-04 at 17 16 13" src="https://github.com/user-attachments/assets/7961fe79-fa20-414a-b01b-e3aab3faace0">



5.  The buttons in “Contacts” should be in the center of the cell
<img width="247" alt="Screenshot 2024-12-04 at 17 18 34" src="https://github.com/user-attachments/assets/8f30ef6c-e275-47c8-a679-82ef84a03617">



6.  Missing chip filtering
<img width="685" alt="Screenshot 2024-12-04 at 17 21 34" src="https://github.com/user-attachments/assets/01811938-404f-42cf-93b5-4bbc43960d85">

2024-12-05 12:01 UTC, tishko0 commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.ts
> +  constructor(private iconService: IgxIconService, private http: HttpClient) { }
When icons resolve they look for the Http Client and if it is null it throws an error. Importing it there fixes it so I am going to leave it for now

2024-12-05 12:02 UTC, tishko0 commented on HR-Portal/src/app/tree-grid1/tree-grid1.component.spec.ts
> +      imports: [BrowserAnimationsModule, IgxTreeGridModule, IgxDatePickerModule, IgxCheckboxModule, TreeGrid1Component]
the test file was generated with the cli. Should we include test file at all? maybe deleting it?

2024-12-05 12:11 UTC, tishko0 commented
> Also could you move the whole `HR-Portal` project folder under `.projects/` at least for now. Until we figure out the main app and its structure.



> 1. Missing “Clear sort” button. The order of the button is different from the design in Figma
> 
> Implementation: <img alt="Screenshot 2024-12-04 at 15 31 47" width="608" src="https://private-user-images.githubusercontent.com/143710956/392755854-3230de17-ebb5-4bf3-931f-210b3b6ba0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU1ODU0LTMyMzBkZTE3LWViYjUtNGJmMy05MzFmLTIxMGIzYjZiYTBiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2FmMDJhMzc5MDNiODliMTM3Y2JiNjAzZTc0NWQ2ZjE1YzE0ZjlhMzNmZmE4NGMwYWFlYTM5Y2U1ZjYzMjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KwSG-_JtAoyophDDd9YDVJxE45_2K6IsLM4jjlu2o08">
> 
> Figma design: <img alt="Screenshot 2024-12-04 at 15 33 48" width="669" src="https://private-user-images.githubusercontent.com/143710956/392756006-d554ee80-3b97-4b0b-b0df-2736fb89fb38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MDA2LWQ1NTRlZTgwLTNiOTctNGIwYi1iMGRmLTI3MzZmYjg5ZmIzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTYxNjUzMGJlMDUzMzAxZjg5MzRiYjFhNTAwMDk0NmEwMWExYWZjNWZmMThjZTM5MDE4MWQ4NzRlYjYyYzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kp6WtHfmnmc_pRaoq816wg0LiGfI5cbLwq2KTZ-FIuw">
> 
> 2. This header should have sorting icon
> 
> <img alt="Screenshot 2024-12-04 at 17 11 25" width="248" src="https://private-user-images.githubusercontent.com/143710956/392756135-d6aafebe-cbb9-4aa9-92a5-3182d513b4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MTM1LWQ2YWFmZWJlLWNiYjktNGFhOS05MmE1LTMxODJkNTEzYjRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODdmZDIwMGJjMzE5Y2MzZmZmOGJkNzY0ZmY2OGIxZDE5ZGExYWZiYjgzYmI3YmFiY2NjOGZiNWNmNGZmM2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hzkFXmVdn9ot6qsRt6Wj84f46pvdNQvsXl8gHfxSIAY">
> 3. “Contacts” should **not** have filtering
> 
> <img alt="Screenshot 2024-12-04 at 17 12 30" width="244" src="https://private-user-images.githubusercontent.com/143710956/392756227-3b5ae95f-30b0-4fbf-8d06-9a10d3adb6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MjI3LTNiNWFlOTVmLTMwYjAtNGZiZi04ZDA2LTlhMTBkM2FkYjZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWFkYjMzNTkyNGM2M2U3MTFjMDA5OTU1NzYxNWViNDEzMjA4MDI1N2E1ZmJhMTdhZWI2ZmM1Zjc3YzU1N2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y6swNUIVfkeQBE7X6OzWzAsMQKzAA6ChHruh09q2xjg">
> 4. The header of “Gross Salary” column should have filtering + sorting. The column should have some data. In Figma the column is populated with data, but probably you can’t see it because of some permissions
> 
> Implementation header: <img alt="Screenshot 2024-12-04 at 17 13 59" width="189" src="https://private-user-images.githubusercontent.com/143710956/392757035-17a10f65-371b-4412-ad1d-bc0f9c6cd546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MDM1LTE3YTEwZjY1LTM3MWItNDQxMi1hZDFkLWJjMGY5YzZjZDU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjM3YWNiNmVhOWVlN2UwOTQwYjhmYzA3MzE4OTk3YmExMzY1MjY5M2JlMDlmYjRhZjI0NWFjODRkN2M5NTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u6R-VoDxC7Tcb5ojJZ6xF2KswBjuTUxROFyqOWGtdJU">
> 
> Figma, “Gross Salary” column: <img alt="Screenshot 2024-12-04 at 17 16 13" width="106" src="https://private-user-images.githubusercontent.com/143710956/392757178-7961fe79-fa20-414a-b01b-e3aab3faace0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MTc4LTc5NjFmZTc5LWZhMjAtNDE0YS1iMDFiLWUzYWFiM2ZhYWNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGU4NGZmNjNlNmMwNDlhZjBjZGQzNjk1MmJiNzAyMzQ5OTg0NTNlNTE3MjU3MTMxYzg4YjVhN2IwMGJlZDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dcd0JwDNJ_S7RFT3Z9i8Yag2rg99AZNPiLqxkacr3XY">
> 
> 5. The buttons in “Contacts” should be in the center of the cell
> 
> <img alt="Screenshot 2024-12-04 at 17 18 34" width="247" src="https://private-user-images.githubusercontent.com/143710956/392757316-8f30ef6c-e275-47c8-a679-82ef84a03617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MzE2LThmMzBlZjZjLWUyNzUtNDdjOC1hNjc5LTgyZWY4NGEwMzYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWE4MWIxMWM2YmQyM2Y2NDA5MzhjNGVjMzI2Y2VkOTlkODllOWEwOGEzN2NlOWE4ODk1MjFkYjI5NzJiOTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o13CHZyANDCLIZLjK4hLU0_WuCXl3d-xUDpvpjglZ_0">
> 6. Missing chip filtering
> 
> <img alt="Screenshot 2024-12-04 at 17 21 34" width="685" src="https://private-user-images.githubusercontent.com/143710956/392757446-01811938-404f-42cf-93b5-4bbc43960d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3NDQ2LTAxODExOTM4LTQwNGYtNDJjZi05M2I1LTRiYmM0Mzk2MGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzkyMzQ3YWQ1OTg4ZWQxYjk4YzUxN2IxOWM2NTJlMWZhODU5M2JhMDY2ZjY3MzlmMmFmOWNhNmU4YTUzYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aSi8ezcr5glLG98FwHiTGPwAFjYQ8yiMzX4ek0_E31g">

Clear sort button shows up when there is sorting and hides  when there is none. This was discussed and it is working. Please communicate this internally again and confirm how you want this to look.

 Sorting has been added to Location
 Filtering removed from Contacts
 Header of gross salary have both sorting and filtering on my end. Can you please check again and send screenshot if they are missing on your end. Also there is content in the column which is right alig [...]

2024-12-05 14:40 UTC, mddragnev requested changes

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +// IMPORTANT: Prior to Ignite UI for Angular version 13 use:
remove this

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +  align-items: center; /* Align items vertically centered */
remove these comments

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +  align-items: center;
to remove duplication this can become smt like this:
```
.flagDiv {
....
...
& igx-icon {
....
}
}
```

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +    --ig-button-text-transform: Capitalize;
move the ng-deep to the top of the file. Also, why do you override `--ig-font-family` like this?
Why override `--ig-button-text-transform` ?

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/assets/responsive.gif
Do you need this assets folder now?

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/localData.ts
This should be somewhere in another folder named data or something like this

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +  constructor(private iconService: IgxIconService, private http: HttpClient) { }
You dont need this `private http: HttpClient` because you have `provideHttpClient()` in your `app.config.ts`

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +    'text-align': 'right',
Do not override the default theming alignment

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +  public formatOptions ={
If you are not using this anythere, please delete.

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/app/app.component.ts
> +import { RouterOutlet } from '@angular/router';
This is not used

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400,600,700" rel="stylesheet">
not needed since you are not using `Titillium web` font-family

2024-12-05 14:40 UTC, mddragnev commented on .projects/HR-Portal/src/styles.scss
> +/* You can add global styles to this file, and also import other style files */
Remove those comments please. Leave the comment for the minireset

2024-12-05 14:42 UTC, mddragnev requested changes
Why is `GitHub` directory outside of `Images` directory? Also, there are a svg and a gif that can go in those `Images` directory too

2024-12-05 17:19 UTC, sdimchevski commented
> > 1. Missing “Clear sort” button. The order of the button is different from the design in Figma
> > 
> > Implementation: <img alt="Screenshot 2024-12-04 at 15 31 47" width="608" src="https://private-user-images.githubusercontent.com/143710956/392755854-3230de17-ebb5-4bf3-931f-210b3b6ba0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU1ODU0LTMyMzBkZTE3LWViYjUtNGJmMy05MzFmLTIxMGIzYjZiYTBiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2FmMDJhMzc5MDNiODliMTM3Y2JiNjAzZTc0NWQ2ZjE1YzE0ZjlhMzNmZmE4NGMwYWFlYTM5Y2U1ZjYzMjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KwSG-_JtAoyophDDd9YDVJxE45_2K6IsLM4jjlu2o08">
> > Figma design: <img alt="Screenshot 2024-12-04 at 15 33 48" width="669" src="https://private-user-images.githubusercontent.com/143710956/392756006-d554ee80-3b97-4b0b-b0df-2736fb89fb38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MDA2LWQ1NTRlZTgwLTNiOTctNGIwYi1iMGRmLTI3MzZmYjg5ZmIzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTYxNjUzMGJlMDUzMzAxZjg5MzRiYjFhNTAwMDk0NmEwMWExYWZjNWZmMThjZTM5MDE4MWQ4NzRlYjYyYzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kp6WtHfmnmc_pRaoq816wg0LiGfI5cbLwq2KTZ-FIuw">
> > 
> > 2. This header should have sorting icon
> > 
> > <img alt="Screenshot 2024-12-04 at 17 11 25" width="248" src="https://private-user-images.githubusercontent.com/143710956/392756135-d6aafebe-cbb9-4aa9-92a5-3182d513b4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MTM1LWQ2YWFmZWJlLWNiYjktNGFhOS05MmE1LTMxODJkNTEzYjRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODdmZDIwMGJjMzE5Y2MzZmZmOGJkNzY0ZmY2OGIxZDE5ZGExYWZiYjgzYmI3YmFiY2NjOGZiNWNmNGZmM2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hzkFXmVdn9ot6qsRt6Wj84f46pvdNQvsXl8gHfxSIAY">
> > 3. “Contacts” should **not** have filtering
> > <img alt="Screenshot 2024-12-04 at 17 12 30" width="244" src="https://private-user-images.githubusercontent.com/143710956/392756227-3b5ae95f-30b0-4fbf-8d06-9a10d3adb6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU2MjI3LTNiNWFlOTVmLTMwYjAtNGZiZi04ZDA2LTlhMTBkM2FkYjZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWFkYjMzNTkyNGM2M2U3MTFjMDA5OTU1NzYxNWViNDEzMjA4MDI1N2E1ZmJhMTdhZWI2ZmM1Zjc3YzU1N2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y6swNUIVfkeQBE7X6OzWzAsMQKzAA6ChHruh09q2xjg">
> > 4. The header of “Gross Salary” column should have filtering + sorting. The column should have some data. In Figma the column is populated with data, but probably you can’t see it because of some permissions
> > Implementation header: <img alt="Screenshot 2024-12-04 at 17 13 59" width="189" src="https://private-user-images.githubusercontent.com/143710956/392757035-17a10f65-371b-4412-ad1d-bc0f9c6cd546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MDM1LTE3YTEwZjY1LTM3MWItNDQxMi1hZDFkLWJjMGY5YzZjZDU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjM3YWNiNmVhOWVlN2UwOTQwYjhmYzA3MzE4OTk3YmExMzY1MjY5M2JlMDlmYjRhZjI0NWFjODRkN2M5NTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u6R-VoDxC7Tcb5ojJZ6xF2KswBjuTUxROFyqOWGtdJU">
> > Figma, “Gross Salary” column: <img alt="Screenshot 2024-12-04 at 17 16 13" width="106" src="https://private-user-images.githubusercontent.com/143710956/392757178-7961fe79-fa20-414a-b01b-e3aab3faace0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MTc4LTc5NjFmZTc5LWZhMjAtNDE0YS1iMDFiLWUzYWFiM2ZhYWNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGU4NGZmNjNlNmMwNDlhZjBjZGQzNjk1MmJiNzAyMzQ5OTg0NTNlNTE3MjU3MTMxYzg4YjVhN2IwMGJlZDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dcd0JwDNJ_S7RFT3Z9i8Yag2rg99AZNPiLqxkacr3XY">
> > 
> > 5. The buttons in “Contacts” should be in the center of the cell
> > 
> > <img alt="Screenshot 2024-12-04 at 17 18 34" width="247" src="https://private-user-images.githubusercontent.com/143710956/392757316-8f30ef6c-e275-47c8-a679-82ef84a03617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3MzE2LThmMzBlZjZjLWUyNzUtNDdjOC1hNjc5LTgyZWY4NGEwMzYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWE4MWIxMWM2YmQyM2Y2NDA5MzhjNGVjMzI2Y2VkOTlkODllOWEwOGEzN2NlOWE4ODk1MjFkYjI5NzJiOTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o13CHZyANDCLIZLjK4hLU0_WuCXl3d-xUDpvpjglZ_0">
> > 6. Missing chip filtering
> > <img alt="Screenshot 2024-12-04 at 17 21 34" width="685" src="https://private-user-images.githubusercontent.com/143710956/392757446-01811938-404f-42cf-93b5-4bbc43960d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTI3MjAsIm5iZiI6MTczMzM5MjQyMCwicGF0aCI6Ii8xNDM3MTA5NTYvMzkyNzU3NDQ2LTAxODExOTM4LTQwNGYtNDJjZi05M2I1LTRiYmM0Mzk2MGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwOTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzkyMzQ3YWQ1OTg4ZWQxYjk4YzUxN2IxOWM2NTJlMWZhODU5M2JhMDY2ZjY3MzlmMmFmOWNhNmU4YTUzYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aSi8ezcr5glLG98FwHiTGPwAFjYQ8yiMzX4ek0_E31g">
> 
> Clear sort button shows up when there is sorting and hides when there is none. This was discussed and it is working. Please communicate this internally again and confirm how you want this to look.
> 
> Sorting has been added to Location Filtering removed from Contacts Header of gross salary have both sorting and filtering on my end. Can you please check again and send screenshot if they are missing on your end. Also there is content in the column which is right aligned as requested. Maybe the width of the grid is more than your display and you do not see the entire grid? I have removed t [...]

2024-12-06 10:02 UTC, tishko0 commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +    --ig-button-text-transform: Capitalize;
I added the fluent typography instead. The button transform is to change the all capital letter case of the buttons as required by design. Am i missing a typography option to do that?

2024-12-06 10:03 UTC, tishko0 commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +    'text-align': 'right',
it was requested by design

2024-12-06 10:03 UTC, tishko0 commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +  public formatOptions ={
using it for the initial sorting

2024-12-06 10:04 UTC, tishko0 commented
Sorted name, re-arranged buttons and location data order

2024-12-06 11:21 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.scss
> +    --ig-button-text-transform: Capitalize;
If the theme is missing a text-transform then either the theme is incorrect or the design

2024-12-06 11:22 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +    'text-align': 'right',
We talked about that we should not override theme default behavior if not mandatory

2024-12-06 12:10 UTC, mddragnev commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +    'text-align': 'right',
Also, when fixing those - please always use formatting for your code. You can enabled formatting even on file saving so that you dont forget

2024-12-10 10:08 UTC, sdimchevski commented
@tishko0 regarding the buttons - you don't need to override them. They should not be All Caps by default. @desig9stein can you help him with this?

2024-12-10 10:37 UTC, tishko0 commented on .projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +    'text-align': 'right',
The overwrites have been removed and document formatted

2024-12-10 15:07 UTC, mddragnev requested changes

2024-12-10 15:07 UTC, mddragnev commented on projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +  public rightAlign = {
You dont need that now

2024-12-10 15:07 UTC, mddragnev commented on projects/HR-Portal/src/app/hr-portal/hr-portal.component.ts
> +  public formatOptions = {
Remove this as well if your are not using it

2024-12-11 09:31 UTC, skrustev approved these changes

2024-12-11 15:11 UTC, merged

2025-01-08 08:01 UTC, yradoeva commented
@tishko0 there should be a padding of 8px between the Avatar and the text in the Name column. 
<img width="775" alt="image" src="https://github.com/user-attachments/assets/7a81f148-e426-403c-b834-eb923beeab89" />