Add fleet management grid sample
IgniteUI/grid-demos pull request #10
Opened 2024-12-13 01:09 UTC by IMinchev64

2024-12-20 14:38 UTC, yradoeva commented
Here are my comments related to design and UX:

1. Would be better the whole Grid to be higher - e.g. 1024px (600px currently is narrow in my opinion). The exact height will depend of course on the container in which it will be embedded on the marketing webpage. By enlarging the height, the visibility of Cost and Utilization tabs will be improved.

2. Would be better to have more than 12 vehicles on the first level. Exactly how many, I’m not sure, maybe at least 25, but I know it will affect the performance so I’ll leave it to you to decide.

3. The Grid should be in S size - with cells’ height of 32px (Toolbar and buttons at the top are OK, already in S). I think the 40px height of the cells and rows currently comes from the avatars, which are 40x40px.

4. The **Avatars** of the car makes should be with custom size 22x22px with border-radius 0.25 rem (4px)
![Keyboard-focusable](https://github.com/user-attachments/assets/e67359f7-234a-4b23-a07f-82f3a93f2ff9)

5. The gap between the Avatar and the Text (“Make” column) should be 8px, also between the Badge and the Text (“Status” column).
<img width="342" alt="image" src="https://github.com/user-attachments/assets/60419ba5-22b9-49bf-839d-71a08ebb5f89" />

6. **Card for GPS coordinates:** the avatar should be M size (64x64px)
The card should be with elevation 24 (as far as I see it is 4)
The card should not have a border.
![Mileage 73,321 mi](https://github.com/user-attachments/assets/5ed22ee8-a054-4b34-9b10-8d2443f79b8a)

7. If possible, the background of the detail area for each row (“behind” the Tabs) should be black (#000000) so the tabs are more distinguishable.
![Pasted Graphic 89](https://github.com/user-attachments/assets/ce3e501d-4d3b-4292-bcde-2a596d724b4e)

8. Detail area, all Tabs - The content area of all Tabs should have 16px paddings from all sides (currently only “Cost” Tab has 10px)
By design: 
<img width="964" alt="Pasted Graphic 87" src="https://github.com/user-attachments/assets/3d5e8082-a8b7-4221-a12a-6d18821456b0" />
Cost Tab: 

![generic](https://github.com/user-attachments/assets/f9c64ab8-e2d3-4da5-8a3a-847920f32a12)


9. **Details Tab: Carousel** - Let’s have photos of the same car in one carousel (not mixing for example red and blue cars). I have uploaded more photos in [One Drive](https://infragisticsinc297-my.sharepoint.com/:f:/g/personal/yradoeva_infragistics_com/EivkCOxtfX9Lo3Kmb9c13h8BRvsgiZ-eD8K2bDA0XCBbKA?e=doeR3Z) and ordered all the photos in separate folders for each vehicle. Let’s have 3 photos in each carousel.

10. **Details Tab:** The Divider’s color between the divs should be —ig-gray-200 with 24% opacity - the same as the bottom border of the grid cells. The font-size of the text should be 0.8125rem (13px) same as in the grid cells.
![igx-divider#igx-divider-11 ig](https://github.com/user-attachments/assets/53a467ca-a0ae-4864-9d6c-cb3bb72bb2e0)

11. **Trip History Tab** is related to the Status of the vehicle:
- “Active” status: we have “Current” badge for the current driver and not ended trips (End: N/A, End Mater: N/A, Distance: N/A and Total Time: N/A)
- “Available” and “In Maintenance” status: we don’t have current driver and the trips should be finished

That screenshot is OK, but I’ve seen some vehicles in “Available” and “In Maintenance” status have current driver, and some in “Active” status have finished trips.
![Pasted Graphic 98](https://github.com/user-attachments/assets/63edf766-c4b7-4289-9fb7-2ba3641e88f3)

12. **Trip History Tab:** There should be a gap of 8px between the Аvatar and the driver’s name and between the name and the Badge in the Driver column
![ohn Davidson](https://github.com/user-attachments/assets/4fa301af-02ef-47d7-abf7-8b5d07c87bba)

13. **Trip History Tab:** the card for the driver’s details should be with elevation 24 (as far as I see it is 4)
The Divider’s color between the divs should be —ig-gray-200 with 24% opacity - the same as the bottom border of the grid cells. The font-size of the text (except the name), should be 0.8125rem (13px) same as in the grid cells. 
The card should not have a border.
![John Davidson](https://github.com/user-attachments/assets/33f86c53-b65d-49c8-8dfb-32cca11c4108)

14. **Maintenance Tab:** the gap between the Badge and the text in Type column should be 8px
![span status-value](https://github.com/user-attachments/assets/5e5b71d6-f13e-4f14-8a30-d021556238fb)

15. **Cost Tab and Utilization Tab:** The border of the chart areas should be 1px, with border-radius 6px.

16. **Cost Tab and Utilization Tab:** data in the charts - if we show on the “Utilization per Month” chart comparison between all 12 months of 2023 and 2024, then we should include also November and December on the “Fuel Costs per Month” chart.

17. **Utilization Tab:** 2023 and 2024 in the legend should not have ‘ ‘ (apostrophes)
![Pasted Graphic 104](https://github.com/user-attachments/assets/fd257a2f-ceee-4c82-a78f-66dee61ead1d)

18. Could the **animation** by opening the cards (for the drivers’ details and for the GPS coordinates) be of type fade-in (fade-out for closing)? Currently, this side opening, swing-right / swing-left, looks a little bit strange, at least to me.

2025-01-14 14:11 UTC, yradoeva commented
1. The **Avatars** of the car makes should be with custom border-radius 0.25 rem (4px) (currently it is 0.5 rem = 8px)
<img width="299" alt="F" src="https://github.com/user-attachments/assets/18431607-feb6-43c6-8850-5671b461c07e" />

2. The ‘**Active’ badge** status should be of type ‘primary’ with primary.500 background color.
<img width="403" alt="Active" src="https://github.com/user-attachments/assets/6e2cb43c-7244-48ab-8d62-dced8cf755d7" />

3. **Trip History Tab, Card for the driver’s details:** The bottom margin of the Close button should be 8px. It looks smaller for some reason (screenshot is when the button is hovered).
<img width="580" alt="Cranbury, NJ" src="https://github.com/user-attachments/assets/0d3f72cc-3b0b-4b47-a0f7-55e46555fd92" />

4. **Card for GPS coordinates:** could you make the location pin a little bit bigger? With height 20px, for example? Or if it’s an igx-icon, with L size (24x24px) (I can’t “catch” it and see exactly what it is)
<img width="79" alt="Pasted Graphic 8" src="https://github.com/user-attachments/assets/be45f9b0-7af0-4cee-924f-a7de77aef511" />

2025-01-15 14:47 UTC, IMinchev64 commented
If running the app with the latest changes after the ["Refactor structure of data and data handling"](https://github.com/IgniteUI/grid-demos/pull/10/commits/fb109dfcde0e6c93b59f1947eec477edb3fa86da) commit you should delete the `.angluar/cache` folder just in case.

2025-01-16 11:32 UTC, MayaKirova approved these changes
Not sure if the images under public/photos/.old are used anywhere. If not they can be removed. Other than that LGTM.

2025-01-16 14:02 UTC, skrustev approved these changes

2025-01-16 15:36 UTC, MarielaTihova commented
1. In the "Trip History" tab the alignment of these columns should be Right like it is in the design.

- Also the ID column in each tab should be right aligned 

![image](https://github.com/user-attachments/assets/8ba296f1-dc42-4536-84f4-655f182045f1)

2. A suggestion about the maps: Is it possible to have them be static, meaning to not have the zoom-in and zoom-out because the pins are being incorrectly placed  when zooming in and out.

2025-01-16 16:57 UTC, MarielaTihova requested changes

2025-01-16 16:57 UTC, MarielaTihova commented on projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
> +  public isLocationOverlayActive = false;
For consistency can you assign type boolean to these two variables as well

2025-01-16 16:57 UTC, MarielaTihova commented on projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
> +    costPerTypePeriod: "ytd",
These values are used in several places ("ytd", "3months", "6months", "12months") . Can you put them in an Enum or some shared object?

2025-01-16 16:57 UTC, MarielaTihova commented on projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
> +  public driverDetails = {
Interface for this so that you can assign it a type

2025-01-16 16:57 UTC, MarielaTihova commented on projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
> +    if (chart == "costsPerType") {
Is it on purpose the usage of `==` instead of `===` ? 

Also can you put all flying around strings in variables? If they are repeating over different files, please put them in a shared location.

2025-01-16 16:57 UTC, MarielaTihova commented on projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
> +    this.driverDetails.name = driverDetails?.name as string;
Please use `driverDetails?.name || ""` instead of `"as string".` This will ensure us that we have an empty string if driverDetails.name has a falsy value. Same goes for all of the fields following

2025-01-17 11:17 UTC, MarielaTihova approved these changes

2025-01-20 14:43 UTC, MarielaTihova approved these changes

2025-01-20 16:39 UTC, merged